In [ ]:
%pip install --upgrade tiktoken -q
%pip install --upgrade openai -q
%pip install tqdm
import tiktoken
import pandas as pd

In [24]:
import os
import tiktoken
from pypdf import PdfReader
import pandas as pd
from tqdm import tqdm

def analyze_bachelor_studies(base_path, model="gpt-4o"):
    all_results = []
    encoding = tiktoken.encoding_for_model(model)
    
    # Die spezifischen Unterordner (Jahre)
    years = ["2023", "2024", "2025"]
    
    print(f"Starte Analyse in: {base_path}\n")

    for year in years:
        year_path = os.path.join(base_path, year)
        year_tokens = 0
        
        if not os.path.exists(year_path):
            print(f"Warnung: Ordner für {year} nicht gefunden unter {year_path}")
            continue
            
        # PDF-Dateien im Jahresordner finden
        pdf_files = [f for f in os.listdir(year_path) if f.endswith('.pdf')]
        
        for file_name in tqdm(pdf_files, desc=f"Verarbeite Jahr {year}"):
            full_path = os.path.join(year_path, file_name)
            
            try:
                reader = PdfReader(full_path)
                file_token_count = 0
                
                for page in reader.pages:
                    page_text = page.extract_text()
                    if page_text:
                        file_token_count += len(encoding.encode(page_text))
                
                year_tokens += file_token_count
                
                all_results.append({
                    "Jahr": year,
                    "Dateiname": file_name,
                    "Seiten": len(reader.pages),
                    "Tokens": file_token_count
                })
                
            except Exception as e:
                print(f" Fehler bei {file_name}: {e}")
        
        # Zwischenergebnis für das Jahr drucken
        print(f"-> Jahr {year} abgeschlossen: {year_tokens:,} Tokens".replace(',', '.'))
        print("-" * 30)

    return pd.DataFrame(all_results)

# --- Pfad Anpassung ---
base_path = "/home/Mike-bazz/Dokumente/Meine_Bachelorarbeit/Studien/Studien/"

# Analyse ausführen
df_studien = analyze_bachelor_studies(base_path)

# --- Finale Auswertung ---
if not df_studien.empty:
    total_tokens = df_studien['Tokens'].sum()
    
    print("\n" + "="*40)
    print("FINALE AUSWERTUNG")
    print("="*40)
    
    # Gruppierte Summen pro Jahr anzeigen
    summary_per_year = df_studien.groupby('Jahr')['Tokens'].sum()
    for year, tokens in summary_per_year.items():
        print(f"Summe Tokens {year}: {tokens:>12,}".replace(',', '.'))
    
    print("-" * 40)
    print(f"GESAMTANZAHL TOKENS: {total_tokens:>12,}".replace(',', '.'))
    print("="*40)
    
    # Tabelle anzeigen
    display(df_studien)
else:
    print("Keine Daten gefunden.")

Starte Analyse in: /home/Mike-bazz/Dokumente/Meine_Bachelorarbeit/Studien/Studien/

Verarbeite Jahr 2023: 0it [00:00, ?it/s]

-> Jahr 2023 abgeschlossen: 0 Tokens
------------------------------

Verarbeite Jahr 2024:  28%|█████▌              | 57/204 [01:25<02:58,  1.21s/it]

 Fehler bei 2024_Jun_057.pdf: Limit reached while decompressing. 3511972 bytes remaining.

Verarbeite Jahr 2024:  52%|█████████▉         | 107/204 [03:42<02:27,  1.52s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Jahr 2024:  53%|██████████         | 108/204 [03:43<01:51,  1.16s/it]

 Fehler bei 2024_Sep_108.pdf: Cannot find Root object in pdf

Verarbeite Jahr 2024:  88%|████████████████▊  | 180/204 [06:08<00:43,  1.80s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Jahr 2024:  89%|████████████████▊  | 181/204 [06:09<00:30,  1.31s/it]

 Fehler bei 2024_Dec_184.pdf: Cannot find Root object in pdf

Verarbeite Jahr 2024: 100%|███████████████████| 204/204 [06:54<00:00,  2.03s/it]

-> Jahr 2024 abgeschlossen: 5.684.591 Tokens
------------------------------

Verarbeite Jahr 2025:  22%|████▍               | 45/205 [01:12<06:47,  2.54s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key

 Fehler bei 2023_Dec_191.pdf: Cannot find Root object in pdf

Verarbeite Jahr 2025:  24%|████▉               | 50/205 [01:19<04:09,  1.61s/it]could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
Verarbeite Jahr 2025:  28%|█████▋              | 58/205 [01:35<04:04,  1.66s/it]Object 851 0 not defined.
Object 1245 0 not defined.
Impossible to decode XFormObject /x9: 'NoneType' object is not subscriptable
Object 1320 0 not defined.
Impossible to decode XFormObject /x24: 'NoneType' object is not subscriptable
Impossible to decode XFormObject /x25: 'NoneType' object is not subscriptable
Impossible to decode XFormObject /x26: 'NoneType' object is not subscriptable
Impossible to decode XFormObject /x27: 'NoneType' object is not subscriptable
Verarbeite Jahr 2025:  52%|█████████▊         | 106/205 [02:56<02:41,  1.63s/it]Impossible to decode XFormObject /Im7: 'NullObject' object is not subscriptable
Impossible to decode XFormObject /Im15: 'NullObject' object is not subscriptable
Verarbeite Jahr 2025:  68%|████████████▉      | 139/205 [03:59<01:26,  1.31s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Jahr 2025:  68%|████████████▉      | 140/205 [03:59<01:06,  1.02s/it]

 Fehler bei 2023_Mar_043.pdf: Cannot find Root object in pdf

Verarbeite Jahr 2025:  69%|█████████████▏     | 142/205 [04:02<01:18,  1.24s/it]could not convert string to float: b'0.00-43464566' : FloatObject (b'0.00-43464566') invalid; use 0.0 instead
Verarbeite Jahr 2025:  86%|████████████████▍  | 177/205 [05:25<00:57,  2.05s/it]could not convert string to float: b'0.000000000000-2842171' : FloatObject (b'0.000000000000-2842171') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-2842171' : FloatObject (b'0.000000000000-2842171') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
Verarbeite Jahr 2025:  95%|█████████████████▉ | 194/205 [05:52<00:14,  1.32s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Jahr 2025:  95%|██████████████████ | 195/205 [05:52<00:09,  1.01it/s]

 Fehler bei 2023_Sep_135.pdf: Cannot find Root object in pdf

Verarbeite Jahr 2025:  97%|██████████████████▎| 198/205 [05:57<00:08,  1.24s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Jahr 2025:  97%|██████████████████▍| 199/205 [05:57<00:05,  1.03it/s]

 Fehler bei 2023_Sep_139.pdf: Cannot find Root object in pdf

Verarbeite Jahr 2025: 100%|███████████████████| 205/205 [06:08<00:00,  1.80s/it]

-> Jahr 2025 abgeschlossen: 5.235.260 Tokens
------------------------------

========================================
FINALE AUSWERTUNG
========================================
Summe Tokens 2024:    5.684.591
Summe Tokens 2025:    5.235.260
----------------------------------------
GESAMTANZAHL TOKENS:   10.919.851
========================================

     Jahr         Dateiname  Seiten  Tokens
0    2024  2024_Mar_001.pdf      30   25326
1    2024  2024_Mar_002.pdf      31   32212
2    2024  2024_Mar_003.pdf      30   29705
3    2024  2024_Mar_004.pdf      50   46315
4    2024  2024_Mar_005.pdf      27   22726
..    ...               ...     ...     ...
397  2025  2023_Sep_141.pdf      23   21052
398  2025  2023_Sep_142.pdf      28   28403
399  2025  2023_Sep_143.pdf      21   18029
400  2025  2023_Sep_144.pdf      26   24332
401  2025  2023_Sep_145.pdf      35   30487

[402 rows x 4 columns]

In [28]:
import os
import tiktoken
from pypdf import PdfReader
import pandas as pd
from tqdm import tqdm
import warnings
import re

warnings.filterwarnings("ignore")

def analyze_bachelor_studies_final(base_path, embedding_model="text-embedding-3-large"):
    all_results = []
    
    # Der korrekte Tokenizer für die v3-Embedding Modelle
    encoding = tiktoken.encoding_for_model(embedding_model)
    
    pdf_tasks = []
    for root, _, files in os.walk(base_path):
        for file in files:
            if file.lower().endswith(".pdf"):
                pdf_tasks.append((root, file))
    
    print(f"Gefundene Dateien insgesamt: {len(pdf_tasks)}")

    for root, file_name in tqdm(pdf_tasks, desc="Verarbeite Dateien"):
        full_path = os.path.join(root, file_name)
        folder_year = os.path.basename(root)
        
        # Extrahiere die Nummer aus dem Dateinamen (z.B. 146 aus "2023_Dec_146.pdf")
        # Wir suchen nach einer Ziffernfolge am Ende vor dem .pdf
        match = re.search(r'(\d+)\.pdf$', file_name, re.IGNORECASE)
        file_number = int(match.group(1)) if match else 0
        
        try:
            reader = PdfReader(full_path, strict=False)
            file_token_count = 0
            
            for page in reader.pages:
                try:
                    text = page.extract_text()
                    if text:
                        file_token_count += len(encoding.encode(text))
                except:
                    continue 
            
            all_results.append({
                "Jahr": folder_year,
                "Nr": file_number,  # Für die Sortierung
                "Dateiname": file_name,
                "Seiten": len(reader.pages),
                "Tokens": file_token_count
            })
        except:
            continue

    df = pd.DataFrame(all_results)
    
    # Sortierung: Erst nach Jahr, dann nach der extrahierten Nummer
    if not df.empty:
        df = df.sort_values(by=['Jahr', 'Nr']).reset_index(drop=True)
        
    return df

# --- Ausführung ---
path = "/home/Mike-bazz/Dokumente/Meine_Bachelorarbeit/Studien/Studien/"
df_studien = analyze_bachelor_studies_final(path)

# --- Auswertung ---
if not df_studien.empty:
    print("\n" + "="*45)
    print(f"TOKEN-AUSWERTUNG (Modell: text-embedding-3-large)")
    print("="*45)
    
    summary = df_studien.groupby('Jahr')['Tokens'].sum()
    for year in sorted(summary.index):
        print(f"Jahr {year}: {summary[year]:>20,}".replace(',', '.'))
    
    print("-" * 45)
    print(f"GESAMT-TOKENS: {df_studien['Tokens'].sum():>18,}".replace(',', '.'))
    print("="*45)
    
    pd.set_option('display.max_rows', None)
    display(df_studien)

Gefundene Dateien insgesamt: 647

Verarbeite Dateien:  34%|███████              | 217/647 [08:23<12:53,  1.80s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Dateien:  54%|███████████▎         | 349/647 [13:00<07:26,  1.50s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Dateien:  65%|█████████████▋       | 422/647 [15:25<07:00,  1.87s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Dateien:  70%|██████████████▊      | 455/647 [16:25<05:07,  1.60s/it]Impossible to decode XFormObject /Im7: 'NullObject' object is not subscriptable
Impossible to decode XFormObject /Im15: 'NullObject' object is not subscriptable
Verarbeite Dateien:  75%|███████████████▊     | 488/647 [17:29<03:30,  1.32s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Dateien:  82%|█████████████████▏   | 528/647 [18:19<01:49,  1.09it/s]could not convert string to float: b'0.00-43464566' : FloatObject (b'0.00-43464566') invalid; use 0.0 instead
Verarbeite Dateien:  87%|██████████████████▎  | 563/647 [19:34<02:35,  1.85s/it]could not convert string to float: b'0.000000000000-2842171' : FloatObject (b'0.000000000000-2842171') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-2842171' : FloatObject (b'0.000000000000-2842171') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.00-39672852' : FloatObject (b'0.00-39672852') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
could not convert string to float: b'0.000000000000-5684342' : FloatObject (b'0.000000000000-5684342') invalid; use 0.0 instead
Verarbeite Dateien:  89%|██████████████████▊  | 578/647 [19:52<01:11,  1.04s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Dateien:  98%|████████████████████▌| 632/647 [21:05<00:33,  2.26s/it]incorrect startxref pointer(1)
parsing for Object Streams
Cannot find "/Root" key in trailer
Searching object with "/Catalog" key
Verarbeite Dateien:  98%|████████████████████▋| 637/647 [21:11<00:12,  1.29s/it]could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
could not convert string to float: b'0.00-10' : FloatObject (b'0.00-10') invalid; use 0.0 instead
Verarbeite Dateien: 100%|████████████████████▉| 645/647 [21:24<00:02,  1.38s/it]Object 851 0 not defined.
Object 1245 0 not defined.
Impossible to decode XFormObject /x9: 'NoneType' object is not subscriptable
Object 1320 0 not defined.
Impossible to decode XFormObject /x24: 'NoneType' object is not subscriptable
Impossible to decode XFormObject /x25: 'NoneType' object is not subscriptable
Impossible to decode XFormObject /x26: 'NoneType' object is not subscriptable
Impossible to decode XFormObject /x27: 'NoneType' object is not subscriptable
Verarbeite Dateien: 100%|█████████████████████| 647/647 [21:36<00:00,  2.00s/it]

=============================================
TOKEN-AUSWERTUNG (Modell: text-embedding-3-large)
=============================================
Jahr 2023:            5.190.357
Jahr 2024:            5.742.068
Jahr 2025:            6.914.327
---------------------------------------------
GESAMT-TOKENS:         17.846.752
=============================================

     Jahr   Nr         Dateiname  Seiten  Tokens
0    2023    1  2023_Mar_001.pdf      38   32644
1    2023    2  2023_Mar_002.pdf      33   34026
2    2023    3  2023_Mar_003.pdf      24   19981
3    2023    4  2023_Mar_004.pdf      28   27729
4    2023    5  2023_Mar_005.pdf      28   25701
5    2023    6  2023_Mar_006.pdf      33   37538
6    2023    7  2023_Mar_007.pdf      30   41723
7    2023    8  2023_Mar_008.pdf      26   21502
8    2023    9  2023_Mar_009.pdf      27   29424
9    2023   10  2023_Mar_010.pdf      25   20271
10   2023   11  2023_Mar_011.pdf      26   25554
11   2023   12  2023_Mar_012.pdf      29   27654
12   2023   13  2023_Mar_013.pdf      33   34050
13   2023   14  2023_Mar_014.pdf      22   21621
14   2023   15  2023_Mar_015.pdf      30   27621
15   2023   16  2023_Mar_016.pdf      25   24554
16   2023   17  2023_Mar_017.pdf      29   23996
17   2023   18  2023_Mar_018.pdf      27   27224
18   2023   19  2023_Mar_019.pdf      24   19701
19   2023   20  2023_Mar_020.pdf      39   50002
20   2023   21  2023_Mar_021.pdf      27   27118
21   2023   22  2023_Mar_022.pdf      27   23177
22   2023   23  2023_Mar_023.pdf      37   26452
23   2023   24  2023_Mar_024.pdf      24   28435
24   2023   25  2023_Mar_025.pdf      29   26153
25   2023   26  2023_Mar_026.pdf      20   18555
26   2023   27  2023_Mar_027.pdf      30   26505
27   2023   28  2023_Mar_028.pdf      35   28992
28   2023   29  2023_Mar_029.pdf      36   39272
29   2023   30  2023_Mar_030.pdf      21   19021
30   2023   31  2023_Mar_031.pdf      27   25867
31   2023   32  2023_Mar_032.pdf      22   21926
32   2023   33  2023_Mar_033.pdf      32   28902
33   2023   34  2023_Mar_034.pdf      22   21700
34   2023   35  2023_Mar_035.pdf      28   30475
35   2023   36  2023_Mar_036.pdf      29   33630
36   2023   37  2023_Mar_037.pdf      26   19890
37   2023   38  2023_Mar_038.pdf      25   26155
38   2023   39  2023_Mar_039.pdf      28   25647
39   2023   40  2023_Mar_040.pdf      24   21636
40   2023   41  2023_Mar_041.pdf      40   35704
41   2023   42  2023_Mar_042.pdf      24   25255
42   2023   44  2023_Mar_044.pdf      22   18696
43   2023   45  2023_Mar_045.pdf      35   32784
44   2023   46  2023_Jun_046.pdf      24   20793
45   2023   47  2023_Jun_047.pdf      24   23059
46   2023   48  2023_Jun_048.pdf      22   21756
47   2023   49  2023_Jun_049.pdf      26   27013
48   2023   50  2023_Jun_050.pdf      31   32428
49   2023   51  2023_Jun_051.pdf      27   27084
50   2023   52  2023_Jun_052.pdf      24   25094
51   2023   53  2023_Jun_053.pdf      25   20582
52   2023   54  2023_Jun_054.pdf      27   23297
53   2023   55  2023_Jun_055.pdf      27   32418
54   2023   56  2023_Jun_056.pdf      34   27430
55   2023   57  2023_Jun_057.pdf      22   19940
56   2023   58  2023_Jun_058.pdf      33   32517
57   2023   59  2023_Jun_059.pdf      37   33725
58   2023   60  2023_Jun_060.pdf      22   19330
59   2023   61  2023_Jun_061.pdf      39   30064
60   2023   62  2023_Jun_062.pdf      28   24587
61   2023   63  2023_Jun_063.pdf      31   20732
62   2023   64  2023_Jun_064.pdf      25   21273
63   2023   65  2023_Jun_065.pdf      25   19738
64   2023   66  2023_Jun_066.pdf      32   28793
65   2023   67  2023_Jun_067.pdf      30   26589
66   2023   68  2023_Jun_068.pdf      24   24148
67   2023   69  2023_Jun_069.pdf      22   21456
68   2023   70  2023_Jun_070.pdf      21   19781
69   2023   71  2023_Jun_071.pdf      23   21872
70   2023   72  2023_Jun_072.pdf      27   25430
71   2023   73  2023_Jun_073.pdf      27   25387
72   2023   74  2023_Jun_074.pdf      34   31319
73   2023   75  2023_Jun_075.pdf      21   18301
74   2023   76  2023_Jun_076.pdf      25   21256
75   2023   77  2023_Jun_077.pdf      33   30193
76   2023   78  2023_Jun_078.pdf      27   25816
77   2023   79  2023_Jun_079.pdf      26   25710
78   2023   80  2023_Jun_080.pdf      23   20129
79   2023   81  2023_Jun_081.pdf      22   18083
80   2023   82  2023_Jun_082.pdf      21   19559
81   2023   83  2023_Sep_083.pdf      29   26321
82   2023   84  2023_Sep_084.pdf      32   29816
83   2023   85  2023_Sep_085.pdf      25   25239
84   2023   86  2023_Sep_086.pdf      25   22987
85   2023   87  2023_Sep_087.pdf      33   31370
86   2023   88  2023_Sep_088.pdf      28   30846
87   2023   89  2023_Sep_089.pdf      30   27071
88   2023   90  2023_Sep_090.pdf      26   23473
89   2023   91  2023_Sep_091.pdf      27   24401
90   2023   92  2023_Sep_092.pdf      32   26969
91   2023   93  2023_Sep_093.pdf      31   31329
92   2023   94  2023_Sep_094.pdf      40   37765
93   2023   95  2023_Sep_095.pdf      20   14518
94   2023   96  2023_Sep_096.pdf      27   22844
95   2023   97  2023_Sep_097.pdf      28   20318
96   2023   98  2023_Sep_098.pdf      29   25458
97   2023   99  2023_Sep_099.pdf      40   28446
98   2023  100  2023_Sep_100.pdf      33   28957
99   2023  101  2023_Sep_101.pdf      28   25946
100  2023  102  2023_Sep_102.pdf      30   26633
101  2023  103  2023_Sep_103.pdf      36   44397
102  2023  104  2023_Sep_104.pdf      27   26465
103  2023  105  2023_Sep_105.pdf      33   33209
104  2023  106  2023_Sep_106.pdf      42   38667
105  2023  107  2023_Sep_107.pdf      30   28410
106  2023  108  2023_Sep_108.pdf      27   25432
107  2023  109  2023_Sep_109.pdf      30   26205
108  2023  110  2023_Sep_110.pdf      37   33474
109  2023  111  2023_Sep_111.pdf      29   24823
110  2023  112  2023_Sep_112.pdf      32   24498
111  2023  113  2023_Sep_113.pdf      26   24545
112  2023  114  2023_Sep_114.pdf      24   22050
113  2023  115  2023_Sep_115.pdf      32   27694
114  2023  116  2023_Sep_116.pdf      32   31668
115  2023  117  2023_Sep_117.pdf      25   30416
116  2023  118  2023_Sep_118.pdf      28   26028
117  2023  119  2023_Sep_119.pdf      20   18172
118  2023  120  2023_Sep_120.pdf      26   25100
119  2023  121  2023_Sep_121.pdf      22   23281
120  2023  122  2023_Sep_122.pdf      29   27136
121  2023  123  2023_Sep_123.pdf      24   21700
122  2023  124  2023_Sep_124.pdf      27   26390
123  2023  126  2023_Sep_126.pdf      30   30532
124  2023  127  2023_Sep_127.pdf      27   27877
125  2023  128  2023_Sep_128.pdf      23   23360
126  2023  130  2023_Sep_130.pdf      24   24138
127  2023  131  2023_Sep_131.pdf      28   26207
128  2023  132  2023_Sep_132.pdf      20   18890
129  2023  133  2023_Sep_133.pdf      29   27305
130  2023  134  2023_Sep_134.pdf      26   30458
131  2023  136  2023_Sep_136.pdf      28   27463
132  2023  137  2023_Sep_137.pdf      24   24183
133  2023  138  2023_Sep_138.pdf      28   28137
134  2023  140  2023_Sep_140.pdf      24   23504
135  2023  141  2023_Sep_141.pdf      23   21094
136  2023  142  2023_Sep_142.pdf      28   28527
137  2023  143  2023_Sep_143.pdf      21   18437
138  2023  144  2023_Sep_144.pdf      26   24429
139  2023  145  2023_Sep_145.pdf      35   30641
140  2023  146  2023_Dec_146.pdf      30   26100
141  2023  147  2023_Dec_147.pdf      30   26354
142  2023  148  2023_Dec_148.pdf      32   29060
143  2023  149  2023_Dec_149.pdf      25   17733
144  2023  150  2023_Dec_150.pdf      26   24477
145  2023  151  2023_Dec_151.pdf      25   22543
146  2023  152  2023_Dec_152.pdf      23   22812
147  2023  153  2023_Dec_153.pdf      24   24290
148  2023  154  2023_Dec_154.pdf      25   23489
149  2023  155  2023_Dec_155.pdf      24   24095
150  2023  156  2023_Dec_156.pdf      30   30198
151  2023  157  2023_Dec_157.pdf      36   30221
152  2023  158  2023_Dec_158.pdf      34   31524
153  2023  159  2023_Dec_159.pdf      24   22776
154  2023  160  2023_Dec_160.pdf      25   24149
155  2023  161  2023_Dec_161.pdf      23   18059
156  2023  162  2023_Dec_162.pdf      25   22198
157  2023  163  2023_Dec_163.pdf      28   29816
158  2023  164  2023_Dec_164.pdf      24   23271
159  2023  165  2023_Dec_165.pdf      29   27112
160  2023  166  2023_Dec_166.pdf      31   29114
161  2023  167  2023_Dec_167.pdf      31   30973
162  2023  168  2023_Dec_168.pdf      30   29247
163  2023  169  2023_Dec_169.pdf      23   21860
164  2023  170  2023_Dec_170.pdf      26   23288
165  2023  171  2023_Dec_171.pdf      26   22169
166  2023  172  2023_Dec_172.pdf      26   25074
167  2023  173  2023_Dec_173.pdf      24   22697
168  2023  174  2023_Dec_174.pdf      39   35677
169  2023  175  2023_Dec_175.pdf      30   22182
170  2023  176  2023_Dec_176.pdf      33   23717
171  2023  177  2023_Dec_177.pdf      23   21240
172  2023  178  2023_Dec_178.pdf      26   21003
173  2023  179  2023_Dec_179.pdf      29   24638
174  2023  180  2023_Dec_180.pdf      29   30030
175  2023  181  2023_Dec_181.pdf      32   26690
176  2023  182  2023_Dec_182.pdf      26   25991
177  2023  183  2023_Dec_183.pdf      28   30163
178  2023  184  2023_Dec_184.pdf      28   23108
179  2023  185  2023_Dec_185.pdf      20   16356
180  2023  187  2023_Dec_187.pdf      29   24717
181  2023  188  2023_Dec_188.pdf      22   49661
182  2023  189  2023_Dec_189.pdf      30   29137
183  2023  190  2023_Dec_190.pdf      22   22223
184  2023  192  2023_Dec_192.pdf      30   27201
185  2023  193  2023_Dec_193.pdf      26   27723
186  2023  194  2023_Dec_194.pdf      23   22856
187  2023  195  2023_Dec_195.pdf      28   21841
188  2023  196  2023_Dec_196.pdf      40   36533
189  2023  197  2023_Dec_197.pdf      32   29653
190  2023  198  2023_Dec_198.pdf      29   28308
191  2023  199  2023_Dec_199.pdf      27   26412
192  2023  200  2023_Dec_200.pdf      28   27666
193  2023  201  2023_Dec_201.pdf      29   25010
194  2023  202  2023_Dec_202.pdf      28   25897
195  2023  203  2023_Dec_203.pdf      25   22840
196  2023  204  2023_Dec_204.pdf      29   28048
197  2023  205  2023_Dec_205.pdf      26   22343
198  2024    1  2024_Mar_001.pdf      30   25401
199  2024    2  2024_Mar_002.pdf      31   32232
200  2024    3  2024_Mar_003.pdf      30   29839
201  2024    4  2024_Mar_004.pdf      50   46650
202  2024    5  2024_Mar_005.pdf      27   22778
203  2024    6  2024_Mar_006.pdf      27   26021
204  2024    7  2024_Mar_007.pdf      30   30226
205  2024    8  2024_Mar_008.pdf      29   25690
206  2024    9  2024_Mar_009.pdf      21   18992
207  2024   10  2024_Mar_010.pdf      26   24293
208  2024   11  2024_Mar_011.pdf      31   27887
209  2024   12  2024_Mar_012.pdf      39   32487
210  2024   13  2024_Mar_013.pdf      29   28811
211  2024   14  2024_Mar_014.pdf      25   23623
212  2024   15  2024_Mar_015.pdf      30   31210
213  2024   16  2024_Mar_016.pdf      29   27038
214  2024   17  2024_Mar_017.pdf      33   32398
215  2024   18  2024_Mar_018.pdf      21   18954
216  2024   19  2024_Mar_019.pdf      29   24971
217  2024   20  2024_Mar_020.pdf      28   26471
218  2024   21  2024_Mar_021.pdf      35   27895
219  2024   22  2024_Mar_022.pdf      28   27430
220  2024   23  2024_Mar_023.pdf      26   21069
221  2024   24  2024_Mar_024.pdf      30   22464
222  2024   25  2024_Mar_025.pdf      29   27278
223  2024   26  2024_Mar_026.pdf      34   26034
224  2024   27  2024_Mar_027.pdf      28   27744
225  2024   28  2024_Mar_028.pdf      25   25630
226  2024   29  2024_Mar_029.pdf      29   23259
227  2024   30  2024_Mar_030.pdf      25   23863
228  2024   31  2024_Mar_031.pdf      32   38943
229  2024   32  2024_Mar_032.pdf      23   23486
230  2024   33  2024_Mar_033.pdf      38   31154
231  2024   34  2024_Mar_034.pdf      26   21255
232  2024   35  2024_Mar_035.pdf      27   24940
233  2024   36  2024_Mar_036.pdf      28   26297
234  2024   37  2024_Mar_037.pdf      34   31114
235  2024   38  2024_Mar_038.pdf      37   36455
236  2024   39  2024_Mar_039.pdf      27   23226
237  2024   40  2024_Mar_040.pdf      31   33070
238  2024   41  2024_Mar_041.pdf      22   23864
239  2024   42  2024_Jun_042.pdf      25   23030
240  2024   43  2024_Jun_043.pdf      32   31426
241  2024   44  2024_Jun_044.pdf      33   27301
242  2024   45  2024_Jun_045.pdf      32   26165
243  2024   46  2024_Jun_046.pdf      31   31323
244  2024   47  2024_Jun_047.pdf      33   32357
245  2024   48  2024_Jun_048.pdf      28   36070
246  2024   49  2024_Jun_049.pdf      31   29654
247  2024   50  2024_Jun_050.pdf      27   28053
248  2024   51  2024_Jun_051.pdf      22   21917
249  2024   52  2024_Jun_052.pdf      29   28566
250  2024   53  2024_Jun_053.pdf      31   24764
251  2024   54  2024_Jun_054.pdf      25   22305
252  2024   55  2024_Jun_055.pdf      29   26999
253  2024   56  2024_Jun_056.pdf      26   24413
254  2024   57  2024_Jun_057.pdf      29   26304
255  2024   58  2024_Jun_058.pdf      27   25119
256  2024   59  2024_Jun_059.pdf      25   25607
257  2024   60  2024_Jun_060.pdf      27   23334
258  2024   61  2024_Jun_061.pdf      37   41934
259  2024   62  2024_Jun_062.pdf      28   26579
260  2024   63  2024_Jun_063.pdf      30   26675
261  2024   64  2024_Jun_064.pdf      27   32940
262  2024   65  2024_Jun_065.pdf      27   21909
263  2024   66  2024_Jun_066.pdf      27   22436
264  2024   67  2024_Jun_067.pdf      25   24289
265  2024   68  2024_Jun_068.pdf      32   28452
266  2024   69  2024_Jun_069.pdf      27   28625
267  2024   70  2024_Jun_070.pdf      34   26332
268  2024   71  2024_Jun_071.pdf      26   22999
269  2024   72  2024_Jun_072.pdf      39   32937
270  2024   73  2024_Jun_073.pdf      35   31305
271  2024   74  2024_Jun_074.pdf      24   28586
272  2024   75  2024_Jun_075.pdf      27   45205
273  2024   76  2024_Jun_076.pdf      32   33111
274  2024   77  2024_Jun_077.pdf      30   31657
275  2024   78  2024_Jun_078.pdf      33   30824
276  2024   79  2024_Jun_079.pdf      24   22978
277  2024   80  2024_Jun_080.pdf      27   24804
278  2024   81  2024_Jun_081.pdf      30   28037
279  2024   82  2024_Jun_082.pdf      28   30248
280  2024   83  2024_Jun_083.pdf      26   24755
281  2024   84  2024_Jun_084.pdf      29   26515
282  2024   85  2024_Jun_085.pdf      34   34531
283  2024   86  2024_Jun_086.pdf      39   35992
284  2024   87  2024_Jun_087.pdf      41   34937
285  2024   88  2024_Sep_088.pdf      24   21429
286  2024   89  2024_Sep_089.pdf      29   25402
287  2024   90  2024_Sep_090.pdf      48   38894
288  2024   91  2024_Sep_091.pdf      33   31371
289  2024   92  2024_Sep_092.pdf      35   24293
290  2024   93  2024_Sep_093.pdf      34   30675
291  2024   94  2024_Sep_094.pdf      24   19626
292  2024   95  2024_Sep_095.pdf      25   23241
293  2024   96  2024_Sep_096.pdf      50   38202
294  2024   97  2024_Sep_097.pdf      24   21828
295  2024   98  2024_Sep_098.pdf      23   22846
296  2024   99  2024_Sep_099.pdf      28   30161
297  2024  100  2024_Sep_100.pdf      33   28353
298  2024  101  2024_Sep_101.pdf      48   40289
299  2024  102  2024_Sep_102.pdf      27   24668
300  2024  103  2024_Sep_103.pdf      29   32001
301  2024  104  2024_Sep_104.pdf      30   28079
302  2024  105  2024_Sep_105.pdf      30   25259
303  2024  106  2024_Sep_106.pdf      35   31719
304  2024  107  2024_Sep_107.pdf      27   25601
305  2024  109  2024_Sep_109.pdf      60   50143
306  2024  110  2024_Sep_110.pdf      30   27914
307  2024  111  2024_Sep_111.pdf      35   31298
308  2024  112  2024_Sep_112.pdf      32   34653
309  2024  113  2024_Sep_113.pdf      23   20413
310  2024  114  2024_Sep_114.pdf      27   26055
311  2024  115  2024_Sep_115.pdf      27   25612
312  2024  116  2024_Sep_116.pdf      24   22763
313  2024  117  2024_Sep_117.pdf      23   22855
314  2024  118  2024_Sep_118.pdf      31   35422
315  2024  119  2024_Sep_119.pdf      29   28028
316  2024  120  2024_Sep_120.pdf      35   26721
317  2024  121  2024_Sep_121.pdf      27   24596
318  2024  122  2024_Sep_122.pdf      26   22308
319  2024  123  2024_Sep_123.pdf      22   21910
320  2024  124  2024_Sep_124.pdf      26   25023
321  2024  125  2024_Sep_125.pdf      31   28479
322  2024  126  2024_Sep_126.pdf      26   25228
323  2024  127  2024_Sep_127.pdf      41   39422
324  2024  128  2024_Sep_128.pdf      29   27444
325  2024  129  2024_Sep_129.pdf      25   24887
326  2024  130  2024_Sep_130.pdf      27   24789
327  2024  131  2024_Sep_131.pdf      30   23348
328  2024  132  2024_Sep_132.pdf      32   25871
329  2024  133  2024_Sep_133.pdf      24   19377
330  2024  134  2024_Sep_134.pdf      32   32138
331  2024  135  2024_Sep_135.pdf      29   25088
332  2024  136  2024_Sep_136.pdf      26   27639
333  2024  137  2024_Sep_137.pdf      27   26327
334  2024  138  2024_Sep_138.pdf      26   30563
335  2024  139  2024_Sep_139.pdf      27   30014
336  2024  140  2024_Dec_140.pdf      24   25427
337  2024  141  2024_Sep_141.pdf      37   36351
338  2024  142  2024_Sep_142.pdf      31   29350
339  2024  143  2024_Sep_143.pdf      35   32157
340  2024  144  2024_Sep_144.pdf      27   25631
341  2024  145  2024_Sep_145.pdf      27   23951
342  2024  146  2024_Sep_146.pdf      24   32797
343  2024  147  2024_Sep_147.pdf      30   35861
344  2024  148  2024_Sep_148.pdf      25   27118
345  2024  149  2024_Dec_149.pdf      42   49736
346  2024  150  2024_Dec_150.pdf      32   28632
347  2024  151  2024_Dec_151.pdf      29   25909
348  2024  152  2024_Dec_152.pdf      42   37406
349  2024  153  2024_Dec_153.pdf      29   33044
350  2024  155  2024_Dec_155.pdf      27   46894
351  2024  156  2024_Dec_156.pdf      25   20884
352  2024  157  2024_Dec_157.pdf      31   25942
353  2024  158  2024_Dec_158.pdf      32   31334
354  2024  159  2024_Dec_159.pdf      22   22881
355  2024  160  2024_Dec_160.pdf      33   36599
356  2024  161  2024_Dec_161.pdf      24   25250
357  2024  162  2024_Dec_162.pdf      32   33777
358  2024  163  2024_Dec_163.pdf      26   33615
359  2024  164  2024_Dec_164.pdf      34   28686
360  2024  166  2024_Dec_166.pdf      32   25836
361  2024  167  2024_Dec_167.pdf      29   28404
362  2024  168  2024_Dec_168.pdf      34   34219
363  2024  169  2024_Dec_169.pdf      27   27368
364  2024  170  2024_Dec_170.pdf      31   26446
365  2024  171  2024_Dec_171.pdf      31   29319
366  2024  172  2024_Dec_172.pdf      29   29634
367  2024  173  2024_Dec_173.pdf      34   29726
368  2024  174  2024_Dec_174.pdf      19   22271
369  2024  175  2024_Dec_175.pdf      21   22508
370  2024  176  2024_Dec_176.pdf      33   30273
371  2024  178  2024_Dec_178.pdf      29   30194
372  2024  179  2024_Dec_179.pdf      31   30718
373  2024  180  2024_Dec_180.pdf      26   27280
374  2024  181  2024_Dec_181.pdf      28   26056
375  2024  182  2024_Dec_182.pdf      27   24259
376  2024  183  2024_Dec_183.pdf      32   28461
377  2024  185  2024_Dec_185.pdf      25   24198
378  2024  186  2024_Dec_186.pdf      44   37033
379  2024  187  2024_Dec_187.pdf      26   23203
380  2024  188  2024_Dec_188.pdf      33   30521
381  2024  189  2024_Dec_189.pdf      30   27925
382  2024  190  2024_Dec_190.pdf      26   31925
383  2024  192  2024_Dec_192.pdf      26   25153
384  2024  193  2024_Dec_193.pdf      22   23430
385  2024  194  2024_Dec_194.pdf      32   47011
386  2024  195  2024_Dec_195.pdf      26   35321
387  2024  196  2024_Dec_196.pdf      31   30906
388  2024  197  2024_Dec_197.pdf      28   22418
389  2024  198  2024_Dec_198.pdf      30   32755
390  2024  199  2024_Dec_199.pdf      26   24720
391  2024  200  2024_Dec_200.pdf      27   23549
392  2024  201  2024_Dec_201.pdf      30   23854
393  2024  202  2024_Dec_202.pdf      26   26822
394  2024  203  2024_Dec_203.pdf      36   32211
395  2024  204  2024_Dec_204.pdf      28   24509
396  2024  205  2024_Dec_205.pdf      29   26964
397  2024  206  2024_Dec_206.pdf      35   45404
398  2024  207  2024_Dec_207.pdf      24   22781
399  2024  209  2024_Dec_209.pdf      22   20245
400  2025    1  2025_Mar_001.pdf      49   40272
401  2025    3  2025_Mar_003.pdf      26   26060
402  2025    4  2025_Mar_004.pdf      32   32447
403  2025    5  2025_Mar_005.pdf      32   31975
404  2025    6  2025_Mar_006.pdf      28   25663
405  2025    7  2025_Mar_007.pdf      24   23149
406  2025    8  2025_Mar_008.pdf      23   22399